### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username, password, billing address, phone number, email address, license plate and credit card details) in order to use services and information that are exclusively available to registered users. 

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#1]
**Acceptance Criteria:**

- [x] Upon failure, an error is displayed, and the user is redirected (back) to the register screen. A register error can be that a username is already taken, or the phone number does not match the correct (CH) format. In addition, an invalid license plate or invalid credit card details can lead to a registration failure. The license plate is valid if it contains exactly two characters that make up a cantonal abbreviation and at least one number (CH format). A credit card is valid if it consists of exactly 16 numbers. The validity of the credit card number is, however, not verified.
- [x] Upon successful user registration, the overview dashboard of the UI is shown, and the user is automatically logged in.
- [x] The creation date of a user and a user ID are saved to the internal database record.
- [x] Logged-in users can log out and log back into their registered profile.

**Development Tasks:**

- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#45
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#46
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#47
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#67
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#33
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#1
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#2
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#3
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#4
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#5
- [x] #94
- [x] #111
- [x] #112
- [x] #149
