### ISSUE TITLE
As a logged-in user, I want to be able to pay for my past usages of parking spaces with my registered credit card in order to easily settle my outstanding bills. 

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#12]
**Acceptance Criteria:**

- [x] Each entry that has the payment status “outstanding” has a button which allows the user to pay the parking costs associated with the respective entry by credit card. 
- [x] After successful payment, the payment status of an entry should be changed to “paid” .
- [x] After successful payment, the two action-fields defined in sopra-fs22-group-03/sopra-fs22-group-03-server#11 (“Pay” and “Split”) should yield no action when clicked, i.e. the buttons are disabled.
- [x] After successful payment, the overall outstanding balance of the user is reduced by the paid amount.

**Development Tasks:**
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#62
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#97
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#98
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#119
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#120
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#153 
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#43
