### ISSUE TITLE
As a logged-in user, I want to be able to immediately be notified of requested “Split Bills” and have the possibility to decide whether or not to accept the split.

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#121]
**Acceptance Criteria:**

- [x] After the first user requests an invoice split, the other user should immediately
receive a notification (e.g., a pop-up on the screen) of the bill split. He/she can then
accept or decline the split.
- [x] If the (second) user accepts the invoice split, the amount is automatically added to
his/her outstanding bills.
- [x] If the (second) user declines the invoice split, the invoice is not added to his/her
outstanding bills.

**Development Tasks:**
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#31
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#32
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#33
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#34
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#41
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#42
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#44
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#45
