### ISSUE TITLE
As a logged-in user, I want to be able to split the amount of a bill with status “outstanding” between myself and another registered user in order to coordinate our shared payment of the parking space.

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#13]
**Acceptance Criteria:**

- [ ] Each entry that has the payment status “outstanding” has a button which allows the
user to split the billed amount between him-/herself and another registered user.
- [ ] If the (second) user accepts the invoice split, the first user is notified (immediately)
and his/her outstanding amount of the split bill is reduced by the corresponding
amount.
- [ ] If the (second) user declines the invoice split, the first user is notified (immediately)
of the denial and the amount of the initial bill remains unchanged.

**Development Tasks:**
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#63
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#72
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#64
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#65
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#66
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#24
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#25
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#26
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#27
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#28
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#29
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#30
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#131
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#132
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#134
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#135
- [x] #146
- [x] #147
- [x] #148
- [x] #153 
- [x] #154
- [x] #163
