### ISSUE TITLE
As a logged-in user, I want to edit my own user profile in order to set/update my personal information. 

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#2]
**Acceptance Criteria:**

- [ ] By clicking on an edit button in the user-profile view, the logged-in user is able to change all of its provided credentials (see sopra-fs22-group-03/sopra-fs22-group-03-server#1). 
- [ ] The constraints on credentials outlined in sopra-fs22-group-03/sopra-fs22-group-03-server#1 (username, phone number, license plate and credit card) apply for these changes. 
- [ ] A registered user can only change its own credentials and not these of other users.
- [ ] After changing and saving the new user profile data, the user is redirected (back) to its user profile page and the new/changed data is displayed.

**Development Tasks:**

- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#35
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#18
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#19
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#20
- [x] #111 
- [x] #112 
- [x] #149
- [x] #162
