### ISSUE TITLE
As a logged-in user, I want to delete my own user profile since I switched to public transport and don’t need car parking spaces anymore. 

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#3]
**Acceptance Criteria:**

- [ ] By clicking on a “delete” button in the user profile the user is prompted if the user profile should actually be deleted.
- [ ] Upon accepting this prompt, the user profile is deleted (including the history and other personal information) from the database and the current user is redirected to the login page.
- [ ] Entering the credentials of the just deleted user profile will yield an error, since it cannot be found in the database anymore.

**Development Tasks:**

- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#36
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#80
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#81
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#21
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#23
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#111 
- [ ] sopra-fs22-group-03/sopra-fs22-group-03-server#112 
- [ ] #149
