### ISSUE TITLE
As a logged-in user, I want to be able to access an overview page of all car parks in Zurich (incl. the number of free parking spaces for each car park) in order to explore different parking possibilities and plan my car journey accordingly. 

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#5]
**Acceptance Criteria:**

- [x] The car parks and their free parking spaces are listed in tabular form for easy readability.
- [x] By clicking on the name of a car park, the user is redirected to the detailed page of the clicked car park.

**Development Tasks:**

- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#48
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#49
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#68
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#50
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#74
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#51
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#52
- [x] #86
- [x] #87
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#8
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#9
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#6
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#10
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#11
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#7
- [x] #103
- [x] #104
- [x] #113
- [x] #114
- [x] #150

**Comment by rspecker** [comment]
Testing is not finished yet
