### ISSUE TITLE
As a logged-in user, I want to be able to check-in into a specific car park by clicking on a button in the detailed page of the respective car park in order to start the parking meter digitally and allowing me to avoid having to take a paper parking ticket when entering the car park.  

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-server#9]
**Acceptance Criteria:**

- [x] As soon as a user checks-in into a car park, the counter of available parking spaces in this car park is reduced by 1. 
- [x] After a user has checked-in into a car park, a button to check-out of the car park is displayed on the dashboard of the application. This allows the user to easily check-out again after he/she leaves the car park.

**Development Tasks:**
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#56
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#70
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#57
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#58
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#91
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#123
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#128
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#129
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#152
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#150 
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#156
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#167 
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#168
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#169
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#51
